### ISSUE TITLE
시나리오 하나 추가해주세요!

### ISSUE THREAD

**Issue by kagong** [SgCapstone6/sogang-notification-controller#4]
크롤러와 디비를 조금 바꿔서 크롤링한 정보를 하루만 저장할 생각입니다.
이와 관련된 시나리오를 하나 추가해주시면 감사하겠습니다.
ex)
현재 구독 상황 
-> 교목처 교목팀 공지사항 구독 완료
-> command : 최근 글 확인
-> 최근 크롤링 타임에 긁어온 글중 구독 사항에 맞는글 출력
도움말과 시나리오 코드가 추가 된다면 알려주세요!
@wjsdydwo02

**Comment by wjsdydwo02** [comment]
@kagong  "구독 최신글" 로 추가합니다. (3어절은 너무 긴 거 같아서)
