### ISSUE TITLE
게시판 검색 시 그게시판의 url이 나오게 하는건 어떨까요?

### ISSUE THREAD

**Issue by kagong** [SgCapstone6/sogang-notification-controller#5]
공지사항 [url]
월별행사 [url]
이런식으로요

@wjsdydwo02

**Comment by wjsdydwo02** [comment]
그럼 SQL 을 이용해서 URL 을 받아올 수 있나요? 일단 시나리오 틀은 수정해두겠습니다.

**Comment by wjsdydwo02** [comment]
@kagong 시나리오 수정했습니다. "url_list"로 나눠서 url을 저장한다는 가정으로 만들었는데, 다른 구조가 낫다면 알려주세요
